### ISSUE TITLE
Missing package to install rmagick gem

### ISSUE THREAD

**Issue by zirni** [interactive-pioneers/passenger-ruby#4]
Hi folks,

bundling my Gemfile which includes the rmagick gem using this docker image fails.
Need to manually install **apt-get install libmagickwand-dev**

I can make a pull request to add this package to the Dockerfile here?
Wdyt?

Cheers

**Comment by ain** [comment]
Why not. Let's do it.

**Comment by ain** [comment]
Resolved with #5.
